column_width = 100
line_endings = "Unix"
indent_type = "Tabs"
indent_width = 3
quote_style = "AutoPreferDouble"
call_parentheses = "Input"
collapse_simple_statement = "ConditionalOnly"

[sort_requires]
enabled = true
