--[[MIT License Copyright (c) 2025 @hardlyardi

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
]]
do
end
local bench_runner_types = require("../../bench/runner/types")
local bench_types = require("../../bench/types")
local profile_types = require("../../bench/profile/types")

type ProfileRunner = bench_runner_types.ProfileRunner
type Profiler = profile_types.ProfileInterface
type LoadedBench<Parameters...> = bench_types.LoadedBench<Parameters...>
type ProfileDefinition<Parameters...> = profile_types.ProfileDefinition<Parameters...>

local function init<Parameters...>(
	passed_runner: ProfileRunner,
	parameter_generator: () -> Parameters...,
	time: number?
): {
	profiler: (tag: string) -> Profiler,
	profile: (name: string, definition: ProfileDefinition<Parameters...>) -> (),
	done: () -> LoadedBench<Parameters...>,
}
	error("TODO")
end

return { init = init }
